# Generated by Django 5.0.7 on 2024-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductPhotoURL', models.CharField(max_length=255)),
                ('ProductStatus', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=8)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
